In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a.dtype, a.shape

(dtype('int64'), (3,))

In [5]:
b = np.zeros(3, int)
b, b.dtype

(array([0, 0, 0]), dtype('int64'))

In [8]:
c = np.zeros_like(a)
a, c, c.dtype

(array([1, 2, 3]), array([0, 0, 0]), dtype('int64'))

In [9]:
np.empty_like(a)

array([ 94630350794816,  94626719465472, 140659998999248])

In [10]:
np.full_like(a, 7)

array([7, 7, 7])

In [11]:
np.ones_like(a)

array([1, 1, 1])



---



**arange is not especially good at handling floats**

This 0.1 looks like a finite decimal number to us but not to the computer: In binary, it is an infinite fraction and has to be rounded somewhere thus an error. That’s why feeding a step with fractional part to arange is generally a bad idea: You might run into an off-by-one error.

In [12]:
np.arange(0.5, 0.8, 0.1) # errado

array([0.5, 0.6, 0.7, 0.8])

In [13]:
np.arange(0.5, 0.75, 0.1) # "certo"

array([0.5, 0.6, 0.7])

In [14]:
np.linspace(0.5, 0.7, 3) # correto

array([0.5, 0.6, 0.7])



---



**Old-style random numbers generation (deprecated)**

In [15]:
np.random.randint(0, 10, 3) # x in [0,10)

array([8, 7, 5])

In [16]:
np.random.rand(3) # x in [0,1)

array([0.03039686, 0.6955994 , 0.75952657])

In [17]:
np.random.randn(3) # mu = 0, std = 1

array([-0.10130623,  0.89789778, -1.44770319])

In [18]:
np.random.uniform(0, 10, 3) # x in [1,10)

array([3.22795619, 4.48979543, 5.17159613])

**New-style random numbers generation**

In [19]:
rng = np.random.default_rng()

In [20]:
rng.integers(0, 10, 3) # uniform dist, x in [0,10)

array([4, 5, 9])

In [21]:
rng.integers(0, 10, 3, endpoint=True) # uniform dist, x in [0,10]

array([10,  6,  2])

In [22]:
rng.random(3) # uniform dist, x in [0,1)

array([0.60210807, 0.91107203, 0.28684964])

In [23]:
rng.standard_normal(3) # normal, mu = 0, std = 1

array([ 0.59727994,  0.45249913, -0.93109123])

In [24]:
rng.normal(5, 2, 3) # normal, mu = 5, std = 2

array([4.22928328, 5.14033127, 6.83290319])



---



In [25]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [26]:
a[1], a[2:4], a[-2:], a[::2]

(2, array([3, 4]), array([4, 5]), array([1, 3, 5]))

In [27]:
a[[1, 3, 4]]

array([2, 4, 5])

All of the indexing methods presented above except fancy indexing are actually so-called “views”: They don’t store the data and reflect the changes in the original array if it happens to get changed after being indexed.

In [30]:
np.any(a > 3)

True

In [31]:
a[a > 3]

array([4, 5])

In [32]:
np.all(a > 3)

False

In [35]:
a[(a >= 2) & (a < 4)]

array([2, 3])

In [37]:
np.where(a > 2)

(array([2, 3, 4]),)

In [41]:
np.where(a >= 5, 1, 0) # => a[a < 5] = 0; a[a > 5] = 1

array([0, 0, 0, 0, 1])

In [40]:
np.clip(a, 3, 5) # => a[a < 3] = 3; a[a > 5] = 5

array([3, 3, 3, 4, 5])



---



In [44]:
a = np.array([2, 3])
b = np.array([4, 5])

In [47]:
a + b, a - b, a * b, b / a, b // a 

(array([6, 8]),
 array([-2, -2]),
 array([ 8, 15]),
 array([2.        , 1.66666667]),
 array([2, 1]))

In [48]:
a ** 2, np.sqrt(a), np.exp(a), np.log(a)

(array([4, 9]),
 array([1.41421356, 1.73205081]),
 array([ 7.3890561 , 20.08553692]),
 array([0.69314718, 1.09861229]))

In [49]:
np.log(np.exp(a))

array([2., 3.])

In [50]:
np.dot(a, b) # a . b

23

In [51]:
np.cross(a, b) # a x b

array(-2)

In [113]:
a @ a.T # inner product

91

---


In [58]:
a = rng.integers(0, 10, 20)
a

array([6, 3, 5, 7, 5, 9, 7, 5, 3, 6, 1, 4, 9, 8, 7, 9, 9, 2, 8, 0])

In [57]:
a.sort() # in-place, quicksort
a

array([0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 6, 7, 8])

In [59]:
np.sort(a) # returns new sorted array

array([0, 1, 2, 3, 3, 4, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9])



---



In [62]:
a = np.arange(1, 7)
a, a.shape

(array([1, 2, 3, 4, 5, 6]), (6,))

In [63]:
a.reshape(-1, 1) # => a[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
a.reshape(1, -1) # => a[None, :]

array([[1, 2, 3, 4, 5, 6]])

In [75]:
a[:, np.newaxis] # => a[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [68]:
b = a.reshape(2, 3)
b, b.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

Here the -1 argument tells reshape to calculate one of the dimension sizes automatically and None in the square brackets serves as a shortcut for np.newaxis, which adds an empty axis at the designated place.

So, there’s a total of three types of vectors in NumPy: 1D arrays, 2D row vectors, and 2D column vectors. 

In [69]:
b.flatten() # returns a copy

array([1, 2, 3, 4, 5, 6])

In [70]:
b.reshape(-1) # returns a view

array([1, 2, 3, 4, 5, 6])

In [71]:
np.ravel(b) # returns a view when possible

array([1, 2, 3, 4, 5, 6])

In [79]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])



---



In [94]:
a = np.arange(1, 7)
M = a.reshape((2, 3)) # is a matrix

In [95]:
M

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
M.sum()

21

In [97]:
M.sum(axis=0) # columns sum

array([5, 7, 9])

In [98]:
M.sum(axis=1) # rows sum

array([ 6, 15])

The 2D case is somewhat counter-intuitive: you need to specify the dimension to be eliminated, instead of the remaining one you would normally think about.

In [107]:
N = np.ones_like(M)
N

array([[1, 1, 1],
       [1, 1, 1]])

In [101]:
M + N

array([[2, 3, 4],
       [5, 6, 7]])

In [105]:
G = np.full_like(M, 9)
G

array([[9, 9, 9],
       [9, 9, 9]])

In [106]:
M / G # normalization

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667]])

In [108]:
M * N # multiplying several columns at once

array([[1, 2, 3],
       [4, 5, 6]])



---



In [117]:
a = np.arange(1, 13).reshape((4, 3))
b = np.arange(1, 9).reshape((4, 2))
c = np.arange(1, 7).reshape((2, 3))


In [118]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [119]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [120]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.vstack((a, c))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [126]:
y = np.hstack((a, b))
y

array([[ 1,  2,  3,  1,  2],
       [ 4,  5,  6,  3,  4],
       [ 7,  8,  9,  5,  6],
       [10, 11, 12,  7,  8]])

In [131]:
a_, b_ = np.hsplit(y, [3])

In [132]:
a_

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [133]:
b_

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [134]:
a = np.arange(1, 5).reshape((2,2))
a

array([[1, 2],
       [3, 4]])

In [135]:
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [136]:
a.repeat(3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [137]:
a.repeat(3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [139]:
a = np.arange(1, 16).reshape((3, 5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [140]:
np.delete(a, [1, 3], axis=1) # delete columns 1 and 3

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [141]:
np.delete(a, 1, axis=0) # delete row 1

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [142]:
np.insert(a, [1, 2], 0, axis=1)

array([[ 1,  0,  2,  0,  3,  4,  5],
       [ 6,  0,  7,  0,  8,  9, 10],
       [11,  0, 12,  0, 13, 14, 15]])